### ISSUE TITLE
MainView anchorToKeyboard doesn't work right

### ISSUE THREAD

**Issue by RedFox3** [ubports/ubuntu-ui-toolkit#100]
I'm using MainView for my Morph base WebApp. Without qmlscene --scaling argument site looks like desktop version but if I use this argument anchorToKeyboard brings up the view too much.

I replaced anchorToKeyboard with my Connections to solve it but I don't think it's okay.

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
