### ISSUE TITLE
Failed to build on Focal

### ISSUE THREAD

**Issue by rubencarneiro** [ubports/ubuntu-ui-toolkit#101]
fatal error: lttng/tracepoint.h: Ficheiro ou pasta inexistente
   27 | #include <lttng/tracepoint.h>

Project ERROR: Unknown module(s) in QT: svg organizer systeminfo systeminfo-private
make[1]: *** [Makefile:118: sub-toolkit-lib-install_subtargets] Erro 3
make[1]: a sair da pasta "/home/ruben/Transferências/ubuntu-ui-toolkit-focal/build/src"
make: *** [Makefile:66: sub-src-install_subtargets] Erro 2

**Comment by dobey** [comment]
It seems you did not install some of the dependencies which are listed under `Build-Depends` in the `debian/control` file. Are some not available in focal?

**Comment by rubencarneiro** [comment]
well yeah some are missing on focal

**Comment by dobey** [comment]
I think all of those should be there. You need:

```
liblttng-ust-dev
libqt5svg5-dev
```

It seems `qtsystems` was not included in focal though, so you might need to rebuild it first.

**Comment by rubencarneiro** [comment]
> I think all of those should be there. You need:
> 
> ```
> liblttng-ust-dev
> libqt5svg5-dev
> ```
> 
> It seems `qtsystems` was not included in focal though, so you might need to rebuild it first.

even so it failed even qt-systems failes to build from source

**Comment by rubencarneiro** [comment]
so this is borked, a clear instructions how to build should be made if, and i say if it be releasing the focal.
I can see a focal branch so, and our intent is to upgrade core system to 20.04 (focal)

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
