### ISSUE TITLE
Popups blends too much on white contents.

### ISSUE THREAD

**Issue by kugiigi** [ubports/ubuntu-ui-toolkit#102]
The borders of popups like Popover are to subtle and makes them blend with white contents like for example in most websites. In short, they don't popup enough :)

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
