### ISSUE TITLE
OptionSelectorDelegate: Binding loop for "itemHeight"

### ISSUE THREAD

**Issue by matdahl** [ubports/ubuntu-ui-toolkit#104]
The binding
```qml
Component.onCompleted: {
    height = listView.itemHeight = Qt.binding(function() { return childrenRect.height; });
}
```
in `OptionSelectorDelegate.qml:128` causes a `QML ListView: Binding loop detected for property "itemHeight"` warning each time a component of this type is created.

**Comment by matdahl** [comment]
replacing
```qml
Component.onCompleted: {
        height = listView.itemHeight = Qt.binding(function() { return childrenRect.height; });
}
```
by
```qml
Component.onCompleted: {
        height = listView.itemHeight = childrenRect.height
}

onChildrenRectChanged: {
        height = listView.itemHeight = childrenRect.height
}
```
should solve the problem.

**Comment by lduboeuf** [comment]
@matdahl will you PR something for that ? , i've tested locally and binding loops warning are gone.

**Comment by matdahl** [comment]
@lduboeuf done. But I accidentally included the not yet merged changes proposed in the other issue #105 ... Is it better to remove them to make 2 separated PRs or should I merge the PRs, i.e. cancel #106 ?

**Comment by lduboeuf** [comment]
I think it is better having two separate PR as it address two different things

**Comment by matdahl** [comment]
I guess, I successfully got rid of the other commits now.
