### ISSUE TITLE
OptionSelectorDelegate: ReferenceError: modelData is not defined

### ISSUE THREAD

**Issue by matdahl** [ubports/ubuntu-ui-toolkit#105]
When using `OptionSelectorDelegate` with a model of type `ListModel` and leaving option.text==="", an 
```
ReferenceError: modelData is not defined
```
occurs. This can be solved by replacing `src/imports/Components/1.3/OptionSelectorDelegate.qml:324` which currently reads
```qml
text: option.text === "" ? modelData : option.text
```
by
```qml
text: (option.text === "" && typeof modelData !== "undefined") ? modelData : option.text
```

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
