### ISSUE TITLE
Fails to build if XDG_RUNTIME_DIR is not set

### ISSUE THREAD

**Issue by vanyasem** [ubports/ubuntu-ui-toolkit#14]
The build fails on `make install` step if XDG_RUNTIME_DIR is not set in the enviroment:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-builduser'
QQmlComponent: Component is not ready
```

Creating `mkdir -p /tmp/runtime-builduser` manually and setting `XDG_RUNTIME_DIR=/tmp/runtime-builduser` before `make install` solves the issue.

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
