### ISSUE TITLE
UITK tests are failing in Xenial

### ISSUE THREAD

**Issue by UniversalSuperBox** [ubports/ubuntu-ui-toolkit#28]
There are 64 build failures and 59 fatal warnings in [the latest build](https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-ui-toolkit/detail/xenial_-_fix-failing-uitk-tests/6/pipeline) of the UITK on xenial_-_fix-failing-uitk-tests. Until this is resolved, new builds of the UITK cannot be completed and PRs cannot be merged.

A build log is attached.

[uitk-log.txt](https://github.com/ubports/ubuntu-ui-toolkit/files/2642046/uitk-log.txt)

**Comment by jezek** [comment]
Can I ask, how is this testable, please? Thanks.

**Comment by UniversalSuperBox** [comment]
Hmm... I guess "nothing in the UI is broken" is about the only way. I'll move this to Done. Sorry about that
