### ISSUE TITLE
PullToRequest text is not translated

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-ui-toolkit#32]
1) Add PullToRequest element
2) Pull down

Expected: hint text to be translated
Behaviour: text is in English

Workaround: Add a default component and translation strings.

See: https://gitlab.com/ubports/apps/weather-app/issues/42
See: screenshot

![imatge](https://user-images.githubusercontent.com/6640041/52919102-efeed700-32fe-11e9-95ae-2953ab556154.png)

**Comment by cibersheep** [comment]
Ah, it happens Weather app was using the vivid apparmor and sdk. Updating to xenial's fixes this

**Comment by cibersheep** [comment]
Then, it seams that is not fixed.

**Comment by jezek** [comment]
FP2 (2019-W09) - language: sk (slovakia)
- In launcher the text is translated.
- In weather app, the text is NOT translated
- In some other apps (contacts, messages, file manager), there is no text

**Comment by cibersheep** [comment]
It might be because the translation strings have «issues with the translation»
[The string](https://translate.ubports.com/translate/unity8/unity8/sk/?checksum=&offset=&q=pull+to+refresh&search=substring&source=on&target=on&type=all&ignored=False&date=&only_user=&exclude_user=)
[Strings that need attention](https://translate.ubports.com/translate/unity8/unity8/sk/?type=todo)

**Comment by Danfro** [comment]
Translation is fine in weather app (and dash) on my E5 running RC 2019-W09.

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc2019-W09 Reset tablet language to Spanish. Pull down wording in weather app also Spanish.
