### ISSUE TITLE
Expose Dark Style Preference

### ISSUE THREAD

**Issue by bhdouglass** [ubports/ubuntu-ui-toolkit#39]
Once [system-settings#166](https://github.com/ubports/system-settings/issues/166) has been implemented we need a simple way to expose that setting to our apps via the UITK. I'm thinking of something like this:

```
import UserPreferences 1.0

UserPreferences.preferDarkStyle
```

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
