### ISSUE TITLE
PopupUtils Can't Get caller If App Is not Already Open

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-ui-toolkit#43]
I know is a bit specific but:
Having such an app that opens from `UriHandler` (being previously closed)

```
MainView {
   Component.onCompleted: {
      PopupUtils.open(component, caller, parameters)
   }
}
```

Poputils will complain that `caller` doesn't exist but it will work if no `caller` nor `parameters` are passed to the popup

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
