### ISSUE TITLE
Allow displaying ampersand (&) in `leadingActionBar.actions`

### ISSUE THREAD

**Issue by myii** [ubports/ubuntu-ui-toolkit#44]
https://gitlab.com/myii/ut-tweak-tool/merge_requests/66

Attempt | Result
--- | ---
`Apps & Scopes` | Apps Scopes
`Apps \& Scopes` | Apps Scopes
`Apps && Scopes` | Apps \&amp; Scopes

Commit links:

* 9c7abaf
* 4986059

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
