### ISSUE TITLE
Project's topic url no longer work

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-ui-toolkit#55]

**Comment by cibersheep** [comment]
Could you give some more info about this issue?

**Comment by lduboeuf** [comment]
![Capture d’écran de 2020-01-03 12-09-01](https://user-images.githubusercontent.com/11663835/71720404-ea6c8380-2e21-11ea-94bd-9ec9dbbbd394.png)

The link provided does not work

**Comment by cibersheep** [comment]
I see. @UniversalSuperBox maybe we could point to:
https://docs.ubports.com/appdev/

**Comment by UniversalSuperBox** [comment]
Changed to https://docs.ubports.com/appdev/, which should redirect to the user's language (but will probably always fall back to English, I don't trust RTD's translations :P )
