### ISSUE TITLE
ColorUstil js or c++?

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-ui-toolkit#57]
We have this definition: [internal ColorUtils 1.3/colorUtils.js](https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/qmldir#L87) but no `colorUtils.js`

We have a [colorutils.cpp](https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/UbuntuToolkit/colorutils.cpp) though.

Is this a leftover, an error or it is correct like that?

**Comment by bhdouglass** [comment]
Looks like it was probably leftover after switching to the cpp one: https://github.com/ubports/ubuntu-ui-toolkit/commit/275b9778dd8aa70f28065e2fc6000e8ad7546d89
