### ISSUE TITLE
dependencies should be mentioned in the README

### ISSUE THREAD

**Issue by nanu-c** [ubports/ubuntu-ui-toolkit#6]
`app-launch-tracepoints.h:29:30: fatal error: lttng/tracepoint.h: Datei oder Verzeichnis nicht gefunden`

**Comment by patrickathompson** [comment]
I had to instal lttng also

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
