### ISSUE TITLE
 Adding iconName to Button screw its automatic sizing 

### ISSUE THREAD

**Issue by mymike00** [ubports/ubuntu-ui-toolkit#7]
If you add an iconName to a button without a set width anchored to one side only, the sizing isn't correct.

Please find attached 2 screenshots demonstrating this issue: there are 2 buttons, one anchored to the left, the other anchored to the right.
If you set the iconName to anything, the right button will expand way beyond its needed width.

Minimal reproducer:

      import QtQuick 2.4
      import Ubuntu.Components 1.2

      MainView {
          id: mainview
          objectName: "mainView"
          applicationName: "splitthebill.didrocks"

          width: units.gu(40)
          height: units.gu(75)

          Page {

              Button {
                  text: "Reset"
                  color: UbuntuColors.red
                  anchors.left: parent.left
              }

              Button {
                  iconName: "add"
                  text: "Archive"
                  color: UbuntuColors.green
                  anchors.right: parent.right
              }
          }
      }  

from: [launchpad](https://bugs.launchpad.net/ubuntu/+source/ubuntu-ui-toolkit/+bug/1478839)

**Comment by cibersheep** [comment]
Interesting. This still happens currently (Components 1.3 and QtQuick 2.9)
![image](https://user-images.githubusercontent.com/6640041/90323960-049a4280-df69-11ea-997d-6e6288fa0873.png)

![image](https://user-images.githubusercontent.com/6640041/90323997-84281180-df69-11ea-837f-c1e8f4fd8e2f.png)

Let's look somewhere here? 
~~https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/ButtonStyle.qml#L157~~
https://github.com/ubports/ubuntu-ui-toolkit/blob/xenial/src/imports/Components/Themes/Ambiance/1.3/ButtonForeground.qml

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
