### ISSUE TITLE
ComboButton: Scroll does not appear

### ISSUE THREAD

**Issue by lduboeuf** [ubports/ubuntu-ui-toolkit#77]
In address-book-app, edit a contact, click on the comboButton, the scrollbar should be displayed. 
I have this in log:

> <pre>file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.3/ComboButton.qml:397:4: QML Scrollbar: Cannot anchor to an item that isn't a parent or sibling.</pre> QML Scrollb

That is strange because the Scrollbar is a sibling of the flickable
This is reproducible also on toolkit gallery

**Comment by lduboeuf** [comment]
Did a work around on contact edition but would need to be remove later

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
