### ISSUE TITLE
Style: parameter naming different

### ISSUE THREAD

**Issue by maddin200** [ubports/ubuntu-ui-toolkit#86]
/src/UbuntuToolkit/qquickmimedata.cpp line 45:
QQuickMimeData::QQuickMimeData(const QMimeData *mimeData, bool refData, QObject *parent) :
vs include file:
QQuickMimeData(const QMimeData *refData, bool localData = true, QObject *parent = 0);

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
