### ISSUE TITLE
defaultCollection() was replaced by defaultCollectionId()

### ISSUE THREAD

**Issue by vanyasem** [ubports/ubuntu-ui-toolkit#9]
Branch: `bionic`

Fails to building using the latest [qtpim](http://code.qt.io/cgit/qt/qtpim.git/commit/) built from source

```
error: ‘class QtOrganizer::QOrganizerManager’ has no member named ‘defaultCollection’; did you mean ‘defaultCollectionId’?
```

[This commit](http://code.qt.io/cgit/qt/qtpim.git/commit/?id=18e3d741c3526978cdacc88bc260d250918d2080) replaced `defaultCollection()` with `defaultCollectionId()`

**Comment by mariogrip** [comment]
I did this for xenial https://github.com/ubports/ubuntu-ui-toolkit/commit/28721c0b9fd719aedf50352247d876f370571435

**Comment by mardy** [comment]
This has been fixed in the `xenial` branch with commit 4f2691b336dedbbeee66434cfafce211170e659a

**Comment by vanyasem** [comment]
@mardy. Good. Unfortunately I'm talking about `bionic` branch.

**Comment by mardy** [comment]
Ah, sorry for the noise then :-)
