### ISSUE TITLE
Pickers value is reset if other is moving

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-ui-toolkit#93]
- Set an alarm
- Spin minutes
- While still spinning, set seconds

When setting seconds, minutes will reset to its initial value

**Comment by UniversalSuperBox** [comment]
Ubuntu UI Toolkit has moved to https://gitlab.com/ubports/core/lomiri-ui-toolkit. If this issue is still relevant, please file it again at https://gitlab.com/ubports/core/lomiri-ui-toolkit/-/issues.
